# Generated by Django 5.0.4 on 2025-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='scholarship_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('chapter_number', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='study_notes/thumbnails/')),
                ('pdf', models.FileField(upload_to='study_notes/pdfs/')),
            ],
        ),
    ]
